[phases.setup]
nixPkgs = ["nodejs", "npm", "python312"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm install --legacy-peer-deps && npm run build"
]

[start]
cmd = "python startup.py"
